# Specify the parent image from which we build
FROM openjdk:11-jdk

# COPY ./setup_android.sh .

# Set environment variables
ENV COMPILE_SDK="31"
ENV BUILD_TOOLS_VERSION="33.0.0"
ENV NDK_VERSION="23.1.7779620"
ENV SDK_TOOLS_VERSION="9123335"
ENV ANDROID_SDK_ROOT="${PWD}/android-home"
ENV PATH="$PATH:${ANDROID_SDK_ROOT}/cmdline-tools/tools/bin/"
ENV ANDROID_HOME="$ANDROID_SDK_ROOT"

# Update and install necessary packages
RUN apt-get update && \
    apt-get install -y wget tar unzip make

# Create directory and download Android SDK tools
RUN mkdir -p $ANDROID_SDK_ROOT && \
    cd $ANDROID_SDK_ROOT && \
    wget --output-document=cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-${SDK_TOOLS_VERSION}_latest.zip && \
    unzip -d cmdline-tools cmdline-tools.zip && \
    cd cmdline-tools && \
    mv cmdline-tools tools || true && \
    cd .. && \
    rm cmdline-tools.zip

RUN sdkmanager --version

# Accept SDK licenses and install necessary packages
RUN yes | sdkmanager --licenses || true && \
    sdkmanager "platforms;android-$COMPILE_SDK" && \
    sdkmanager "platform-tools" && \
    sdkmanager "build-tools;$BUILD_TOOLS_VERSION"

# Print environment variables for verification
RUN echo "printing android home" && \
    echo $ANDROID_HOME && \
    echo "printing path" && \
    echo $PATH && \
    echo "printing sdk root" && \
    echo $ANDROID_SDK_ROOT && \
    echo "printing compile sdk" && \
    echo $COMPILE_SDK && \
    echo "printing build tools version" && \
    echo $BUILD_TOOLS_VERSION && \
    echo "printing ndk version" && \
    echo $NDK_VERSION && \
    echo "printing sdk tools version" && \
    echo $SDK_TOOLS_VERSION && \
    echo "Android sdk dir content" && \
    ls -la $ANDROID_SDK_ROOT

# CMD ["jshell"]